import type { Site, CustomerContainerView, DriverTrip, Anfahrt, Order, Invoice, ErrorLog, Driver } from './api'

export const SITES: Site[] = [
  {
    siteId: 'site-001',
    customerId: 'cust-demo',
    name: 'Baustelle Eichenweg 45',
    address: 'Eichenweg 45, 10117 Berlin',
    lat: 52.5200,
    lon: 13.4050,
    orientationNote: 'Tor auf der Nordseite, Einfahrt links neben dem Lagergebäude.',
    createdAt: '2026-03-01T08:00:00Z',
    active: true,
  },
  {
    siteId: 'site-002',
    customerId: 'cust-demo',
    name: 'Lager Schönhauser Allee',
    address: 'Schönhauser Allee 12, 10119 Berlin',
    lat: 52.5370,
    lon: 13.4140,
    orientationNote: 'Direkt am Hintereingang, Tor-Code 4812.',
    createdAt: '2026-03-15T10:00:00Z',
    active: true,
  },
  {
    siteId: 'site-003',
    customerId: 'cust-demo',
    name: 'Bürokomplex Hauptstraße',
    address: 'Hauptstraße 99, 10827 Berlin',
    lat: 52.4790,
    lon: 13.3460,
    orientationNote: null,
    createdAt: '2026-04-01T09:00:00Z',
    active: true,
  },
]

export const CONTAINERS: CustomerContainerView[] = [
  {
    bookingId: 'bk-001',
    siteId: 'site-001',
    containerNumber: 'C-1041',
    wasteType: 'Mixed',
    status: 'Filling',
    fillLevel: 0.72,
    lat: 52.5200,
    lon: 13.4050,
    expectedEmptyingAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    bookingId: 'bk-002',
    siteId: 'site-001',
    containerNumber: 'C-0882',
    wasteType: 'Wood',
    status: 'EmptyRequested',
    fillLevel: 0.95,
    lat: 52.5200,
    lon: 13.4050,
    expectedEmptyingAt: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    bookingId: 'bk-003',
    siteId: 'site-002',
    containerNumber: 'C-0331',
    wasteType: 'Metal',
    status: 'Delivered',
    fillLevel: 0.30,
    lat: 52.5370,
    lon: 13.4140,
    expectedEmptyingAt: null,
  },
  {
    bookingId: 'bk-004',
    siteId: 'site-003',
    containerNumber: null,
    wasteType: 'Concrete',
    status: 'Scheduled',
    fillLevel: 0.0,
    lat: 52.4790,
    lon: 13.3460,
    expectedEmptyingAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    bookingId: 'bk-005',
    siteId: 'site-002',
    containerNumber: 'C-0554',
    wasteType: 'Paper',
    status: 'Retrieved',
    fillLevel: 1.0,
    lat: null,
    lon: null,
    expectedEmptyingAt: '2026-04-10T14:00:00Z',
  },
]

const now = new Date()
const tomorrow = new Date(now)
tomorrow.setDate(tomorrow.getDate() + 1)
const dayAfter = new Date(now)
dayAfter.setDate(dayAfter.getDate() + 2)

export const DRIVER_TRIPS: DriverTrip[] = [
  {
    dayBucket: now.toISOString().slice(0, 10),
    driverUserId: 'driver-demo',
    scheduledAt: new Date(now.setHours(8, 30)).toISOString(),
    bookingId: 'bk-002',
    customerId: 'cust-demo',
    siteId: 'site-001',
    containerNumber: 'C-0882',
    wasteType: 'Wood',
    tripKind: 'pickup',
    bookingStatus: 'EmptyRequested',
    siteName: 'Baustelle Eichenweg 45',
    siteAddress: 'Eichenweg 45, 10117 Berlin',
    siteLat: 52.5200,
    siteLon: 13.4050,
    createdAt: '2026-04-24T07:00:00Z',
    reportCompletedAt: null,
  },
  {
    dayBucket: now.toISOString().slice(0, 10),
    driverUserId: 'driver-demo',
    scheduledAt: new Date(now.setHours(10, 0)).toISOString(),
    bookingId: 'bk-003',
    customerId: 'cust-demo',
    siteId: 'site-002',
    containerNumber: 'C-0331',
    wasteType: 'Metal',
    tripKind: 'delivery',
    bookingStatus: 'Delivered',
    siteName: 'Lager Schönhauser Allee',
    siteAddress: 'Schönhauser Allee 12, 10119 Berlin',
    siteLat: 52.5370,
    siteLon: 13.4140,
    createdAt: '2026-04-24T07:00:00Z',
    reportCompletedAt: null,
  },
  {
    dayBucket: tomorrow.toISOString().slice(0, 10),
    driverUserId: 'driver-demo',
    scheduledAt: new Date(tomorrow.setHours(9, 0)).toISOString(),
    bookingId: 'bk-004',
    customerId: 'cust-demo',
    siteId: 'site-003',
    containerNumber: null,
    wasteType: 'Concrete',
    tripKind: 'delivery',
    bookingStatus: 'Scheduled',
    siteName: 'Bürokomplex Hauptstraße',
    siteAddress: 'Hauptstraße 99, 10827 Berlin',
    siteLat: 52.4790,
    siteLon: 13.3460,
    createdAt: '2026-04-24T08:00:00Z',
    reportCompletedAt: null,
  },
]

export const ANFAHRTEN: Record<string, Anfahrt[]> = {
  'site-001': [
    {
      siteId: 'site-001',
      anfahrtId: 'anf-001',
      uploadedByUserId: 'cust-demo',
      uploadedAt: '2026-04-20T14:30:00Z',
      lat: 52.5200,
      lon: 13.4050,
      orientationNote: 'Tor auf der Nordseite, Einfahrt links.',
      videoStorageKey: null,
      videoContentType: null,
      videoSizeBytes: 0,
    },
  ],
  'site-002': [],
  'site-003': [],
}

export const MOCK_DRIVERS: Driver[] = [
  { driverId: 'driver-demo', name: 'Hans Müller' },
  { driverId: 'driver-002', name: 'Klaus Wagner' },
  { driverId: 'driver-003', name: 'Petra Schmidt' },
]

export const MOCK_ORDERS: Order[] = [
  {
    orderId: 'ord-001',
    customerId: 'cust-demo',
    siteId: 'site-001',
    createdAt: '2026-04-22T09:15:00Z',
    requestedDeliveryAt: '2026-04-25T08:00:00Z',
    notes: 'Bitte früh morgens liefern.',
    bookingIds: ['bk-001', 'bk-002'],
    status: 'Filling',
    assignedDriverId: 'driver-demo',
    reports: [],
  },
  {
    orderId: 'ord-002',
    customerId: 'cust-demo',
    siteId: 'site-002',
    createdAt: '2026-04-23T14:00:00Z',
    requestedDeliveryAt: '2026-04-26T10:00:00Z',
    notes: null,
    bookingIds: ['bk-003'],
    status: 'Requested',
    assignedDriverId: null,
    reports: [],
  },
  {
    orderId: 'ord-003',
    customerId: 'cust-demo',
    siteId: 'site-003',
    createdAt: '2026-04-24T11:30:00Z',
    requestedDeliveryAt: null,
    notes: 'Betonschutt, schwer.',
    bookingIds: ['bk-004'],
    status: 'Scheduled',
    assignedDriverId: 'driver-002',
    reports: [],
  },
]

export const MOCK_INVOICES: Invoice[] = [
  {
    invoiceId: 'inv-001',
    customerId: 'cust-demo',
    bookingId: 'bk-005',
    siteId: 'site-002',
    wasteType: 'Paper',
    siteName: 'Lager Schönhauser Allee',
    issuedAt: '2026-04-10T16:00:00Z',
    amount: 180,
    currency: 'EUR',
    status: 'paid',
    weightKg: 1200,
    pricePerKg: 0.15,
    damageCharge: null,
  },
]

export const MOCK_ERROR_LOGS: ErrorLog[] = [
  {
    logId: 'log-001',
    occurredAt: '2026-04-24T22:10:00Z',
    level: 'warn',
    message: 'Anfahrt video upload failed for site-002 — no video provided.',
    context: 'uploadAnfahrt',
  },
  {
    logId: 'log-002',
    occurredAt: '2026-04-23T08:45:00Z',
    level: 'error',
    message: 'Fill level update rejected: booking bk-999 not found.',
    context: 'updateFill',
  },
  {
    logId: 'log-003',
    occurredAt: '2026-04-22T14:00:00Z',
    level: 'info',
    message: 'New order ord-002 created by cust-demo.',
    context: 'createOrder',
  },
]
